" Vundle initialization
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" Airline plugin
Plugin 'bling/vim-airline'

call vundle#end()            " required
filetype plugin indent on    " required

" Airline appear always
set laststatus=2
let g:airline_powerline_fonts = 1